name: Clone Gitlab Repository use vpn
on:
  workflow_dispatch:
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3
      # Cài đặt OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      # Tạo file cấu hình VPN từ GitHub Secret
      - name: Configure VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" | base64 --decode > vpn_config.ovpn
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > vpn_auth.txt

      # Kết nối VPN
      - name: Connect to VPN
        run: |
          sudo openvpn --config vpn_config.ovpn --auth-user-pass vpn_auth.txt --daemon
          sleep 10  # Chờ VPN kết nối

      # Kiểm tra kết nối
      - name: Verify VPN Connection
        run: curl ifconfig.me

      - name: Verify VPN Interface
        run: ip addr show tun0


      
      # # Clone GitLab Repository
      # - name: Clone GitLab Repository
      #   run: |
      #     git clone http://oauth2:${{ secrets.GITLAB_TOKEN }}@git.mediastep.com/hang.pham/GoSELL-Automation.git      
      # - name: List cloned files
      #   run: ls -la ./GoSELL-Automation
