name: Mobile Automation

on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run tests'
          default: "STAG"
          type: choice
          options:
            - CA
            - STAG
            - PROD
            - PREPROD
        languageSF:
          description: 'Language on SSR to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
        languageDB:
          description: 'Language on Dashboard to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup Android SDK and Emulator
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          emulator-options: '-no-window -gpu swiftshader_indirect'
      
      - name: Build project
        run: ./gradlew build

      - name: Start Android emulator
        run: |
          echo "Starting Android emulator..."
          nohup emulator -avd testAVD -no-window -gpu swiftshader_indirect &
          sleep 60  # Đợi emulator khởi động
      
      - name: Run automation tests
        run: ./gradlew connectedAndroidTest
