name: 'Vi test environment variable'
# on:
#   push:
#     branches:
#       - main
# on:
#   schedule:
#     - cron: "30 00 * * *"  # 7:30 AM GMT+7
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Chose environment'
        default: 'STAG'
        type: choice
        options:
          - CA
          - STAG
          - PREPROD
          - PROD
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
          ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
          


 
