name: 'Workflow use available action 1'
on:
  push:
    branches:
      - main
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout source
       uses: action/checkout@v3
     - name: list repositoty
       run: ls -l
